/*
Copyright 2015 Tremolo Security, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 10:43:31 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AppUiConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AppUiConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="uiDecsionClass" type="{http://www.tremolosecurity.com/scale}UiDecisionClassType"/>
 *         &lt;element name="frontPage" type="{http://www.tremolosecurity.com/scale}FrontPageType"/>
 *         &lt;element name="logoutURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="useGenericGroups" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="groupsAttribute" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="workflowName" type="{http://www.w3.org/2001/XMLSchema}string" default="Workflow" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AppUiConfigType", propOrder = {
    "uiDecsionClass",
    "frontPage",
    "logoutURL"
})
public class AppUiConfigType {

    @XmlElement(required = true)
    protected UiDecisionClassType uiDecsionClass;
    @XmlElement(required = true)
    protected FrontPageType frontPage;
    @XmlElement(required = true)
    protected String logoutURL;
    @XmlAttribute(name = "useGenericGroups", required = true)
    protected boolean useGenericGroups;
    @XmlAttribute(name = "groupsAttribute")
    protected String groupsAttribute;
    @XmlAttribute(name = "workflowName")
    protected String workflowName;

    /**
     * Gets the value of the uiDecsionClass property.
     * 
     * @return
     *     possible object is
     *     {@link UiDecisionClassType }
     *     
     */
    public UiDecisionClassType getUiDecsionClass() {
        return uiDecsionClass;
    }

    /**
     * Sets the value of the uiDecsionClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiDecisionClassType }
     *     
     */
    public void setUiDecsionClass(UiDecisionClassType value) {
        this.uiDecsionClass = value;
    }

    /**
     * Gets the value of the frontPage property.
     * 
     * @return
     *     possible object is
     *     {@link FrontPageType }
     *     
     */
    public FrontPageType getFrontPage() {
        return frontPage;
    }

    /**
     * Sets the value of the frontPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrontPageType }
     *     
     */
    public void setFrontPage(FrontPageType value) {
        this.frontPage = value;
    }

    /**
     * Gets the value of the logoutURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogoutURL() {
        return logoutURL;
    }

    /**
     * Sets the value of the logoutURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogoutURL(String value) {
        this.logoutURL = value;
    }

    /**
     * Gets the value of the useGenericGroups property.
     * 
     */
    public boolean isUseGenericGroups() {
        return useGenericGroups;
    }

    /**
     * Sets the value of the useGenericGroups property.
     * 
     */
    public void setUseGenericGroups(boolean value) {
        this.useGenericGroups = value;
    }

    /**
     * Gets the value of the groupsAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupsAttribute() {
        return groupsAttribute;
    }

    /**
     * Sets the value of the groupsAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupsAttribute(String value) {
        this.groupsAttribute = value;
    }

    /**
     * Gets the value of the workflowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowName() {
        if (workflowName == null) {
            return "Workflow";
        } else {
            return workflowName;
        }
    }

    /**
     * Sets the value of the workflowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowName(String value) {
        this.workflowName = value;
    }

}
