/*******************************************************************************
 * Copyright 2015 Tremolo Security, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 08:54:27 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tremolosecurity.scale.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ScaleConfig_QNAME = new QName("http://www.tremolosecurity.com/scale", "ScaleConfig");
    private final static QName _ScalePasswordResetConfig_QNAME = new QName("http://www.tremolosecurity.com/scale", "ScalePasswordResetConfig");
    private final static QName _ScaleRegisterConfig_QNAME = new QName("http://www.tremolosecurity.com/scale", "ScaleRegisterConfig");
    private final static QName _ScaleSingleRequestConfig_QNAME = new QName("http://www.tremolosecurity.com/scale", "ScaleSingleRequestConfig");
    private final static QName _ScaleTOTPConfig_QNAME = new QName("http://www.tremolosecurity.com/scale", "ScaleTOTPConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tremolosecurity.scale.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScalePasswordResetConfigType }
     * 
     */
    public ScalePasswordResetConfigType createScalePasswordResetConfigType() {
        return new ScalePasswordResetConfigType();
    }

    /**
     * Create an instance of {@link ScaleConfigType }
     * 
     */
    public ScaleConfigType createScaleConfigType() {
        return new ScaleConfigType();
    }

    /**
     * Create an instance of {@link ScaleSingleRequestConfigType }
     * 
     */
    public ScaleSingleRequestConfigType createScaleSingleRequestConfigType() {
        return new ScaleSingleRequestConfigType();
    }

    /**
     * Create an instance of {@link ScaleRegisterConfigType }
     * 
     */
    public ScaleRegisterConfigType createScaleRegisterConfigType() {
        return new ScaleRegisterConfigType();
    }

    /**
     * Create an instance of {@link ScaleTOTPConfigType }
     * 
     */
    public ScaleTOTPConfigType createScaleTOTPConfigType() {
        return new ScaleTOTPConfigType();
    }

    /**
     * Create an instance of {@link RegisterFrontPageType }
     * 
     */
    public RegisterFrontPageType createRegisterFrontPageType() {
        return new RegisterFrontPageType();
    }

    /**
     * Create an instance of {@link WorkflowsType }
     * 
     */
    public WorkflowsType createWorkflowsType() {
        return new WorkflowsType();
    }

    /**
     * Create an instance of {@link UiCommonConfigType }
     * 
     */
    public UiCommonConfigType createUiCommonConfigType() {
        return new UiCommonConfigType();
    }

    /**
     * Create an instance of {@link InitParamType }
     * 
     */
    public InitParamType createInitParamType() {
        return new InitParamType();
    }

    /**
     * Create an instance of {@link AttributeType }
     * 
     */
    public AttributeType createAttributeType() {
        return new AttributeType();
    }

    /**
     * Create an instance of {@link TotpFrontPageType }
     * 
     */
    public TotpFrontPageType createTotpFrontPageType() {
        return new TotpFrontPageType();
    }

    /**
     * Create an instance of {@link AppUiConfigType }
     * 
     */
    public AppUiConfigType createAppUiConfigType() {
        return new AppUiConfigType();
    }

    /**
     * Create an instance of {@link PwdResetValidation }
     * 
     */
    public PwdResetValidation createPwdResetValidation() {
        return new PwdResetValidation();
    }

    /**
     * Create an instance of {@link ScaleCommonConfigType }
     * 
     */
    public ScaleCommonConfigType createScaleCommonConfigType() {
        return new ScaleCommonConfigType();
    }

    /**
     * Create an instance of {@link FrontPageType }
     * 
     */
    public FrontPageType createFrontPageType() {
        return new FrontPageType();
    }

    /**
     * Create an instance of {@link PwdResetFrontPageType }
     * 
     */
    public PwdResetFrontPageType createPwdResetFrontPageType() {
        return new PwdResetFrontPageType();
    }

    /**
     * Create an instance of {@link NameValueType }
     * 
     */
    public NameValueType createNameValueType() {
        return new NameValueType();
    }

    /**
     * Create an instance of {@link UiDecisionClassType }
     * 
     */
    public UiDecisionClassType createUiDecisionClassType() {
        return new UiDecisionClassType();
    }

    /**
     * Create an instance of {@link ServicesConfigType }
     * 
     */
    public ServicesConfigType createServicesConfigType() {
        return new ServicesConfigType();
    }

    /**
     * Create an instance of {@link UserAttributesConfigType }
     * 
     */
    public UserAttributesConfigType createUserAttributesConfigType() {
        return new UserAttributesConfigType();
    }

    /**
     * Create an instance of {@link ApprovalsType }
     * 
     */
    public ApprovalsType createApprovalsType() {
        return new ApprovalsType();
    }

    /**
     * Create an instance of {@link RegisterWorkflowType }
     * 
     */
    public RegisterWorkflowType createRegisterWorkflowType() {
        return new RegisterWorkflowType();
    }

    /**
     * Create an instance of {@link ScaleSingleRequestFrontPageType }
     * 
     */
    public ScaleSingleRequestFrontPageType createScaleSingleRequestFrontPageType() {
        return new ScaleSingleRequestFrontPageType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaleConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/scale", name = "ScaleConfig")
    public JAXBElement<ScaleConfigType> createScaleConfig(ScaleConfigType value) {
        return new JAXBElement<ScaleConfigType>(_ScaleConfig_QNAME, ScaleConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScalePasswordResetConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/scale", name = "ScalePasswordResetConfig")
    public JAXBElement<ScalePasswordResetConfigType> createScalePasswordResetConfig(ScalePasswordResetConfigType value) {
        return new JAXBElement<ScalePasswordResetConfigType>(_ScalePasswordResetConfig_QNAME, ScalePasswordResetConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaleRegisterConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/scale", name = "ScaleRegisterConfig")
    public JAXBElement<ScaleRegisterConfigType> createScaleRegisterConfig(ScaleRegisterConfigType value) {
        return new JAXBElement<ScaleRegisterConfigType>(_ScaleRegisterConfig_QNAME, ScaleRegisterConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaleSingleRequestConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/scale", name = "ScaleSingleRequestConfig")
    public JAXBElement<ScaleSingleRequestConfigType> createScaleSingleRequestConfig(ScaleSingleRequestConfigType value) {
        return new JAXBElement<ScaleSingleRequestConfigType>(_ScaleSingleRequestConfig_QNAME, ScaleSingleRequestConfigType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScaleTOTPConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.tremolosecurity.com/scale", name = "ScaleTOTPConfig")
    public JAXBElement<ScaleTOTPConfigType> createScaleTOTPConfig(ScaleTOTPConfigType value) {
        return new JAXBElement<ScaleTOTPConfigType>(_ScaleTOTPConfig_QNAME, ScaleTOTPConfigType.class, null, value);
    }

}
