/*
Copyright 2015 Tremolo Security, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 10:43:31 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScalePasswordResetConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScalePasswordResetConfigType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tremolosecurity.com/scale}ScaleCommonConfigType">
 *       &lt;sequence>
 *         &lt;element name="frontPage" type="{http://www.tremolosecurity.com/scale}PwdResetFrontPageType"/>
 *         &lt;element name="attributes" type="{http://www.tremolosecurity.com/scale}UserAttributesConfigType"/>
 *         &lt;element name="passwordValidation" type="{http://www.tremolosecurity.com/scale}PwdResetValidation"/>
 *         &lt;element name="workflowName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScalePasswordResetConfigType", propOrder = {
    "frontPage",
    "attributes",
    "passwordValidation",
    "workflowName"
})
public class ScalePasswordResetConfigType
    extends ScaleCommonConfigType
{

    @XmlElement(required = true)
    protected PwdResetFrontPageType frontPage;
    @XmlElement(required = true)
    protected UserAttributesConfigType attributes;
    @XmlElement(required = true)
    protected PwdResetValidation passwordValidation;
    @XmlElement(required = true)
    protected String workflowName;

    /**
     * Gets the value of the frontPage property.
     * 
     * @return
     *     possible object is
     *     {@link PwdResetFrontPageType }
     *     
     */
    public PwdResetFrontPageType getFrontPage() {
        return frontPage;
    }

    /**
     * Sets the value of the frontPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link PwdResetFrontPageType }
     *     
     */
    public void setFrontPage(PwdResetFrontPageType value) {
        this.frontPage = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link UserAttributesConfigType }
     *     
     */
    public UserAttributesConfigType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAttributesConfigType }
     *     
     */
    public void setAttributes(UserAttributesConfigType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the passwordValidation property.
     * 
     * @return
     *     possible object is
     *     {@link PwdResetValidation }
     *     
     */
    public PwdResetValidation getPasswordValidation() {
        return passwordValidation;
    }

    /**
     * Sets the value of the passwordValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link PwdResetValidation }
     *     
     */
    public void setPasswordValidation(PwdResetValidation value) {
        this.passwordValidation = value;
    }

    /**
     * Gets the value of the workflowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkflowName() {
        return workflowName;
    }

    /**
     * Sets the value of the workflowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkflowName(String value) {
        this.workflowName = value;
    }

}
