//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 08:54:27 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScaleRegisterConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScaleRegisterConfigType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tremolosecurity.com/scale}ScaleCommonConfigType">
 *       &lt;sequence>
 *         &lt;element name="frontPage" type="{http://www.tremolosecurity.com/scale}RegisterFrontPageType"/>
 *         &lt;element name="attributes" type="{http://www.tremolosecurity.com/scale}UserAttributesConfigType"/>
 *         &lt;element name="termsAndConditions" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="recaptcha" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="uniqueAttribute" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="workflowConfiguration" type="{http://www.tremolosecurity.com/scale}RegisterWorkflowType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleRegisterConfigType", propOrder = {
    "frontPage",
    "attributes",
    "termsAndConditions",
    "recaptcha",
    "uniqueAttribute",
    "workflowConfiguration"
})
public class ScaleRegisterConfigType
    extends ScaleCommonConfigType
{

    @XmlElement(required = true)
    protected RegisterFrontPageType frontPage;
    @XmlElement(required = true)
    protected UserAttributesConfigType attributes;
    @XmlElement(required = true)
    protected String termsAndConditions;
    protected boolean recaptcha;
    protected List<String> uniqueAttribute;
    @XmlElement(required = true)
    protected RegisterWorkflowType workflowConfiguration;

    /**
     * Gets the value of the frontPage property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterFrontPageType }
     *     
     */
    public RegisterFrontPageType getFrontPage() {
        return frontPage;
    }

    /**
     * Sets the value of the frontPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterFrontPageType }
     *     
     */
    public void setFrontPage(RegisterFrontPageType value) {
        this.frontPage = value;
    }

    /**
     * Gets the value of the attributes property.
     * 
     * @return
     *     possible object is
     *     {@link UserAttributesConfigType }
     *     
     */
    public UserAttributesConfigType getAttributes() {
        return attributes;
    }

    /**
     * Sets the value of the attributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserAttributesConfigType }
     *     
     */
    public void setAttributes(UserAttributesConfigType value) {
        this.attributes = value;
    }

    /**
     * Gets the value of the termsAndConditions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermsAndConditions() {
        return termsAndConditions;
    }

    /**
     * Sets the value of the termsAndConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermsAndConditions(String value) {
        this.termsAndConditions = value;
    }

    /**
     * Gets the value of the recaptcha property.
     * 
     */
    public boolean isRecaptcha() {
        return recaptcha;
    }

    /**
     * Sets the value of the recaptcha property.
     * 
     */
    public void setRecaptcha(boolean value) {
        this.recaptcha = value;
    }

    /**
     * Gets the value of the uniqueAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the uniqueAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUniqueAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUniqueAttribute() {
        if (uniqueAttribute == null) {
            uniqueAttribute = new ArrayList<String>();
        }
        return this.uniqueAttribute;
    }

    /**
     * Gets the value of the workflowConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterWorkflowType }
     *     
     */
    public RegisterWorkflowType getWorkflowConfiguration() {
        return workflowConfiguration;
    }

    /**
     * Sets the value of the workflowConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterWorkflowType }
     *     
     */
    public void setWorkflowConfiguration(RegisterWorkflowType value) {
        this.workflowConfiguration = value;
    }

}
