/*
Copyright 2015 Tremolo Security, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 10:43:31 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ScaleTOTPConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScaleTOTPConfigType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.tremolosecurity.com/scale}ScaleCommonConfigType">
 *       &lt;sequence>
 *         &lt;element name="frontPage" type="{http://www.tremolosecurity.com/scale}TotpFrontPageType"/>
 *         &lt;element name="decryptionKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="attributeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleTOTPConfigType", propOrder = {
    "frontPage",
    "decryptionKey",
    "attributeName"
})
public class ScaleTOTPConfigType
    extends ScaleCommonConfigType
{

    @XmlElement(required = true)
    protected TotpFrontPageType frontPage;
    @XmlElement(required = true)
    protected String decryptionKey;
    @XmlElement(required = true)
    protected String attributeName;

    /**
     * Gets the value of the frontPage property.
     * 
     * @return
     *     possible object is
     *     {@link TotpFrontPageType }
     *     
     */
    public TotpFrontPageType getFrontPage() {
        return frontPage;
    }

    /**
     * Sets the value of the frontPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotpFrontPageType }
     *     
     */
    public void setFrontPage(TotpFrontPageType value) {
        this.frontPage = value;
    }

    /**
     * Gets the value of the decryptionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecryptionKey() {
        return decryptionKey;
    }

    /**
     * Sets the value of the decryptionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecryptionKey(String value) {
        this.decryptionKey = value;
    }

    /**
     * Gets the value of the attributeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeName() {
        return attributeName;
    }

    /**
     * Sets the value of the attributeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeName(String value) {
        this.attributeName = value;
    }

}
