/*
Copyright 2015 Tremolo Security, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 10:43:31 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Common configuration for all Scale applications
 * 
 * <p>Java class for ScaleCommonConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScaleCommonConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceConfiguration" type="{http://www.tremolosecurity.com/scale}ServicesConfigType"/>
 *         &lt;element name="UiConfig" type="{http://www.tremolosecurity.com/scale}UiCommonConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleCommonConfigType", propOrder = {
    "serviceConfiguration",
    "uiConfig"
})
@XmlSeeAlso({
    ScalePasswordResetConfigType.class,
    ScaleConfigType.class,
    ScaleRegisterConfigType.class,
    ScaleTOTPConfigType.class
})
public class ScaleCommonConfigType {

    @XmlElement(required = true)
    protected ServicesConfigType serviceConfiguration;
    @XmlElement(name = "UiConfig", required = true)
    protected UiCommonConfigType uiConfig;

    /**
     * Gets the value of the serviceConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesConfigType }
     *     
     */
    public ServicesConfigType getServiceConfiguration() {
        return serviceConfiguration;
    }

    /**
     * Sets the value of the serviceConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesConfigType }
     *     
     */
    public void setServiceConfiguration(ServicesConfigType value) {
        this.serviceConfiguration = value;
    }

    /**
     * Gets the value of the uiConfig property.
     * 
     * @return
     *     possible object is
     *     {@link UiCommonConfigType }
     *     
     */
    public UiCommonConfigType getUiConfig() {
        return uiConfig;
    }

    /**
     * Sets the value of the uiConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiCommonConfigType }
     *     
     */
    public void setUiConfig(UiCommonConfigType value) {
        this.uiConfig = value;
    }

}
