//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.28 at 08:54:27 PM EDT 
//


package com.tremolosecurity.scale.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Common configuration for all Scale applications
 * 
 * <p>Java class for ScaleCommonConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ScaleCommonConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serviceConfiguration" type="{http://www.tremolosecurity.com/scale}ServicesConfigType"/>
 *         &lt;element name="UiConfig" type="{http://www.tremolosecurity.com/scale}UiCommonConfigType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ScaleCommonConfigType", propOrder = {
    "serviceConfiguration",
    "uiConfig"
})
@XmlSeeAlso({
    ScalePasswordResetConfigType.class,
    ScaleConfigType.class,
    ScaleSingleRequestConfigType.class,
    ScaleRegisterConfigType.class,
    ScaleTOTPConfigType.class
})
public class ScaleCommonConfigType {

    @XmlElement(required = true)
    protected ServicesConfigType serviceConfiguration;
    @XmlElement(name = "UiConfig", required = true)
    protected UiCommonConfigType uiConfig;

    /**
     * Gets the value of the serviceConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link ServicesConfigType }
     *     
     */
    public ServicesConfigType getServiceConfiguration() {
        return serviceConfiguration;
    }

    /**
     * Sets the value of the serviceConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServicesConfigType }
     *     
     */
    public void setServiceConfiguration(ServicesConfigType value) {
        this.serviceConfiguration = value;
    }

    /**
     * Gets the value of the uiConfig property.
     * 
     * @return
     *     possible object is
     *     {@link UiCommonConfigType }
     *     
     */
    public UiCommonConfigType getUiConfig() {
        return uiConfig;
    }

    /**
     * Sets the value of the uiConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiCommonConfigType }
     *     
     */
    public void setUiConfig(UiCommonConfigType value) {
        this.uiConfig = value;
    }

}
